config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :show, :edit, :update, :destroy]

  resources :products do
    resources :orders
  end
  resources :products do
    resources :cart
  end

  resources :products do
    member do
      put "like", to: "products#upvote"
      put "dislike", to: "products#downvote"
    end
  end

  resources :products do
    resources :comments
  end

  resources :orders do
    resources :charges
  end
  resources :orders do
    resources :reviews
  end

  get '/cart/:id', to: 'cart#show', as: 'cart'
  get '/AboutUs', to: 'home#aboutus'
  # resources :cart, only: [:show, :index, :create]
  root 'home#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
  # AR classes are singular and capitalized by convention
  has_and_belongs_to_many :products
  belongs_to :user
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
#ArticlesController is inheriting from a special class called ApplicationController
  before_action :authenticate_user!

  def index
    @orders = Order.where(user_id: current_user.id)
  end

  def show
  end

  def new
    @product = Product.find(params[:product_id])
  end

  def edit
  end

  def create
    @product = Product.find(params[:product_id])
    @order = Order.new(orders_params)
    @order.rental_days = (@order.end_date - @order.meetup_date).to_i
    @order.individual_cost = ((@order.rental_days.to_f / 7) * @product.price).round(2)
    @order.status = true
    @order.save

    # OrderMailer.new_order(@product, current_user.id).deliver_now
    if @order.save
      @order.products << @product
      user_session["product"].delete(@product.id)
      redirect_to orders_path
    else
      render plain: 'This is not a create page'
    end
  end

  def update
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path
  end

  private
  def orders_params
    params.require(:order).permit(:user_id, :rental_days, :meetup_date, :end_date, :individual_cost, :product_id => [])
  end

end

app/views/orders/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-8 mt-4">
			<% if @orders.blank? %>
				<h1>No order was made</h1>
			<% else %>
				<h1 style="font-size: 40px"> Your Orders: </h1>
				<hr/>
				<% @orders.each do |order|%>
					<% if order.status === true %>
						<% order.products.each do |op| %>
							<h3> Name: <small class="text-info"> <%= op.name %></small> </h3>
							<%= cl_image_tag(op.product_image, class: "img-fluid showPic profile") %>
							<h3> Price: <small class="text-info"> $<%= op.price %></small> </h3>
							<h3> Number of renting days: <small class="text-info"> <%= order.rental_days %></small></h3>
							<h3> Total Price: <small class="text-info"> $<%= order.individual_cost %></small></h3>
							<%= form_tag order_charges_path(order.id) do %>
							  <article>
							    <% if flash[:error].present? %>
							      <div id="error_explanation">
							        <p><%= flash[:error] %></p>
							      </div>
							    <% end %>
							  </article>
							  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
							          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
							          data-description="Product name: <%= op.name %>"
							          data-amount="<%= order.individual_cost * 100 %>"
							          data-locale="auto"></script>
							<% end %>
							<br/>
							<%= link_to '<i class="fas fa-trash"></i> Delete'.html_safe, order_path(order.id), method: :delete, data: { confirm: 'Are you sure you want to delete this order?' }, class: "btn btn-primary" %>
							<hr/>
						<% end %>
					<% end %>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/orders/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-1 mt-4">
			<h1 class="text-secondary" style="font-size: 40px"> Form for order</h1>
			<%= form_with scope: :order, url: product_orders_path, local: true do |form| %>
				<p>
					<%= form.label :meetup_date, class: 'h3'%><br>
					<%= form.date_field :meetup_date, class: 'form-control'%>
				</p>
				<p>
					<%= form.label :end_date, class: 'h3'%><br>
					<%= form.date_field :end_date, class: 'form-control'%>
				</p>
				<p>
					<%= form.hidden_field :user_id, value: current_user.id %>
					<%= form.hidden_field :product_id, value: @product.id %>
					<%= form.submit :class => "btn btn-info"%>
				</p>
			<% end %>
		</div>
	</div>
</div>