config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :show, :edit, :update, :destroy]

  resources :products do
    resources :orders
  end
  resources :products do
    resources :cart
  end

  resources :products do
    member do
      put "like", to: "products#upvote"
      put "dislike", to: "products#downvote"
    end
  end

  resources :products do
    resources :comments
  end

  resources :orders do
    resources :charges
  end
  resources :orders do
    resources :reviews
  end

  get '/cart/:id', to: 'cart#show', as: 'cart'
  get '/AboutUs', to: 'home#aboutus'
  # resources :cart, only: [:show, :index, :create]
  root 'home#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  # AR classes are singular and capitalized by convention
  has_and_belongs_to_many :orders, dependent: :destroy
  belongs_to :user
  has_many :reviews
  has_many :comments

  acts_as_votable

  geocoded_by :meetup_location  # can also be an IP address
  after_validation :geocode  # auto-fetch coordinates
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
#ArticlesController is inheriting from a special class called ApplicationController
  before_action :authenticate_user!
  def upvote
      @product = Product.find(params[:id])
      @product.upvote_by current_user
      redirect_to products_path
  end

  def downvote
    @product = Product.find(params[:id])
    @product.downvote_by current_user
    redirect_to products_path
  end

  def index
      if params[:term]
        @products = Product.where('name LIKE ?', "%#{params[:term]}%")
      else
        @products = Product.all
      end
  end

  def show
    @product = Product.find(params[:id])
    @user = User.find(@product.user_id)
  end

  def new
    @user = User.find(current_user.id)
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    uploaded_file = params[:product][:product_image].path
    cloudnary_file = Cloudinary::Uploader.upload(uploaded_file)

    params[:product][:product_image] = cloudnary_file['public_id']
    @product = Product.new(products_params)
    @product.save
    if @product.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Product was successfully created.' }
      end
    else
      render 'new'
    end

  end

  def update
    uploaded_file = params[:product][:product_image].path
    cloudnary_file = Cloudinary::Uploader.upload(uploaded_file)

    params[:product][:product_image] = cloudnary_file['public_id']

    @user = User.find(current_user.id)
    @product = Product.find(params[:id])
    @product.update(products_params)
    redirect_to user_path(@user.id)
  end

  def destroy
    @product = Product.find(params[:id])
    @user = User.find(current_user.id)

    @product.destroy
    redirect_to user_path(@user.id)
  end

  private
  def products_params
    params.require(:product).permit(:term, :name, :description, :product_image, :price, :meetup_location, :availability_status, :user_id, :order_id => [])
  end
end

app/views/products/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-1 mt-4">
			<h1>Edit Post</h1>
					<%= form_with model: @product, url: product_path, local: true do |form| %>
						<p>
								<%= form.label :name, class: 'h3'%><br/>
								<%= form.text_field :name, size: "100", class: 'form-control'%>
						</p>
						<p>
							<%= form.label :product_image, class: 'h3' %><br>
							<%= form.file_field :product_image, class: 'form-control'%>
						</p>
						<p>
								<%= form.label :description, class: 'h3' %><br/>
								<%= form.text_area :description, cols: "100", rows: "10",class: 'form-control' %>
						</p>
						<p>
							<%= form.label :price, class: 'h3' %><br>
							<%= form.number_field :price, class: 'form-control' %>
						</p>
						<p>
							<%= form.label :meetup_location, class: 'h3' %><br>
							<%= form.text_field :meetup_location, class: 'form-control' %>
						</p>
						<p>
							<%= form.label :availability_status, class: 'h3' %><br>
							<%= form.select :availability_status, [['Have Stock', true], ['Out of Stock', false]], class: 'form-control'%>
						</p>
						<p>
							<br/>
							<%= form.submit :class => "btn btn-primary" %>
						</p>
					<% end %>
			<%= link_to 'Back', root_path, :class => "text-info" %>
		</div>
	</div>
</div>

app/views/products/index.html.erb
<div class="container-fluid">
	<div class="col-sm-3 mt-4">
  		<h1 style="font-size: 40px"> Products </h1>
  		<hr/>
  </div>
	<div class="row">
			<% @products.each do |product| %>
						<div class="col-sm-3 mt-4">
							<div class="card-group">
								<div class="card">
								  <%= cl_image_tag(product.product_image, class: "card-img-top img-fluid") %>
								  <hr/>
				  					<div class="card-body">
				  							<%= link_to product.name, product_path(product), class: "card-title text-info h3" %>
										    <p class="card-text"><%= truncate(product.description, :length => 100, :separator => ' ') { link_to "read more", product_path(product.id) } %></p>
										    <% if product.user_id != current_user.id %>
										    		<p class="font-italic font-weight-bold">Check out the product by clicking on it's name </p>
										    <% else %>
												    <%= link_to 'Edit' , edit_product_path(product), class: "btn btn-primary" %>
												    <%= link_to 'Delete' , product_path(product.id), method: :delete,
						      data: { confirm: 'Are you sure you want to delete this?' }, class: "btn btn-primary" %>
						     				<% end %>
										</div>
								</div>
							</div>
						<br/>
						</div>
			<% end %>
	</div>
</div>

app/views/products/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-1 mt-4">
			<h1> Create new product</h1>
			<%= form_with scope: :product, url: products_path, local: true do |form| %>
				<p>
					<%= form.label :name, class: 'h3'%><br>
					<%= form.text_field :name, class: 'form-control'%>
				</p>

				<p>
					<%= form.label :product_image, class: 'h3' %><br>
					<%= form.file_field :product_image, class: 'form-control'%>
				</p>
				<p>
					<%= form.label :description, class: 'h3' %><br>
					<%= form.text_area :description, class: 'form-control' %>
				</p>
				<p>
					<%= form.label :price, class: 'h3' %><br>
					<%= form.number_field :price, class: 'form-control' %>
				</p>
				<p>
					<%= form.label :preferred_meetup_location, class: 'h3' %><br>
					<%= form.text_field :meetup_location, class: 'form-control' %>
				</p>
				<p>
					<%= form.label :availability_status, class: 'h3' %><br>
					<%= form.select :availability_status, ['Have Stock', 'Out of Stock'], class: 'form-control'%>
				</p>

				<p>
					<%= form.hidden_field :user_id, value: current_user.id %>
					<%= form.submit :class => "btn btn-info"%>
				</p>
			<% end %>
		</div>
	</div>
</div>

app/views/products/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 mt-4" >
				<h1 style="font-size: 40px"> Product: <%=@product.name %></h1>
				<%= cl_image_tag(@product.product_image, class: "img-fluid showPic profile") %>
				<p style="border: 5px solid black; padding: 10px; border-radius: 10px; margin-top: 10px"> <%=@product.description%></p>
				<h3 class="text-info" style="font-size: 30px">Supplier's name:</h3>
				<p style="font-size: 20px"> <%=@user.name %></p>
				<h3 class="text-info" style="font-size: 30px">Price per week:</h3>
				<p style="font-size: 20px"> <%=@product.price %></p>
		</div>
		<div class="col-sm-6 mt-4 product-details">
				<h3 class="text-info" style="font-size: 30px">Preferred Location for Meetup: </h3>
				<p style="font-size: 20px"> <%= @product.meetup_location %></p>
				<div id="map"></div>
				<br/>
				<h3 class="text-info" style="font-size: 30px">Availability: </h3>
				<% if @product.availability_status == true %>
						<p class="text-success" style="font-size: 20px">Currently have stock </p>
				<% else %>
						<p class="text-danger" style="font-size: 20px">Out of stock</p>
				<%end%>
				<% if @product.user_id != current_user.id %>
					<% if @product.availability_status === true %>
			    	<%= link_to '<i class="fas fa-cart-plus"></i> Cart'.html_safe, product_cart_index_path(@product), class: "btn btn-primary" %>
			    	<%= link_to like_product_path(@product), method: :put, class: "btn btn-primary" do %>
			    			<i class="fas fa-thumbs-up"></i>
			    			<%= @product.get_upvotes.size %>
			    	<% end %>
			    	<%= link_to dislike_product_path(@product), method: :put, class: "btn btn-primary" do %>
			    			<i class="fas fa-thumbs-down"></i>
			    			<%= @product.get_downvotes.size %>
			    	<% end %>
			    <% else %>
			    	<p>There is currently no stock available! Please check in later! </p>
			    <% end %>
				<% else %>
			    	<%= link_to 'Edit' , edit_product_path(@product), class: "btn btn-primary btn-xs" %>
			    	<%= link_to 'Delete' , product_path(@product), method: :delete,
data: { confirm: 'Are you sure you want to delete this?' }, class: "btn btn-primary btn-xs" %>
				<% end %>
		</div>
	<div class="col-sm-6 mt-4" >
		<h1 style="font-size: 40px">Comments</h1>
		<%= link_to 'View all comments', product_comments_path(@product), class: "btn btn-primary" %>
		<p></p>
	</div>

	<div class="row">

	</div>
  <script>
	  var map;
    function initMap() {
      map = new google.maps.Map(document.getElementById('map'), {
        center: {lat:<%= @product.latitude %>, lng:<%= @product.longitude %>},
        zoom: 13
      });

		  var marker = new google.maps.Marker({
		    position: {lat:<%= @product.latitude %>, lng:<%= @product.longitude %>},
		    map: map,
		    title: 'Hello World!'
		  });
    }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA5XAE_t6YUsO_4vl-eitIVMmt2kgSmHjM&callback=initMap"
  async defer>
  </script>
</div>