config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :show, :edit, :update, :destroy]

  resources :products do
    resources :orders
  end
  resources :products do
    resources :cart
  end

  resources :products do
    member do
      put "like", to: "products#upvote"
      put "dislike", to: "products#downvote"
    end
  end

  resources :products do
    resources :comments
  end

  resources :orders do
    resources :charges
  end
  resources :orders do
    resources :reviews
  end

  get '/cart/:id', to: 'cart#show', as: 'cart'
  get '/AboutUs', to: 'home#aboutus'
  # resources :cart, only: [:show, :index, :create]
  root 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentOutLoud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <style>
         /* Always set the map height explicitly to define the size of the div
          * element that contains the map. */
         #map {
           height: 500px;
         }
    </style>
  </head>

  <body>
  	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  	  <a class="navbar-brand" href="/"><i class="fas fa-trophy"></i> RENT OUT LOUD</a>
  	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarNav">
  	    <ul class="navbar-nav mr-auto">
  	      <li class="nav-item active">
  	        <a class="nav-link" href="/AboutUs">About Us </a>
  	      </li>
  	      <% if !user_signed_in? %>
  	      	<li class="nav-item active">
  	      	  <a class="nav-link" href="/users/sign_up">Sign Up</a>
  	      	</li>
  	      	<li>
  	      		<a class="nav-link active" href="/users/sign_in">Sign In</a>
  	      	</li>
  	      <% else %>
  	      	<li class="nav-item active">
  	      			<%= link_to '<i class="fas fa-shopping-cart"></i> Cart'.html_safe, cart_path(current_user.id), class: 'nav-link'%>
  	      	</li>
  	      	<li class="nav-item active">
  	      		<%= link_to '<i class="fab fa-product-hunt"></i> Products'.html_safe, products_path, class: 'nav-link'%>
  	      	</li>
  	      	<li class="nav-item active">
  	      		<%= link_to '<i class="far fa-smile-wink"></i> Profile'.html_safe, user_path(current_user.id), class: 'nav-link'%>
  	      	</li>
  	      	<li class="nav-item active">
  	      		<%= link_to '<i class="fas fa-file-invoice-dollar"></i> Orders'.html_safe, orders_path, class: 'nav-link'%>
  	      	</li>
  	      	<li class="nav-item active">
	  	      	<%= link_to '<i class="fas fa-door-open"></i> Logout'.html_safe, destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure?'}, class: 'nav-link' %>
	  	      </li>
  	      <% end %>
  	    </ul>
  	    <%= form_tag(products_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
  	      <%= text_field_tag :term, params[:term], placeholder: 'Search products...', class: 'form-control mr-sm-2'%>
  	      <%= submit_tag 'Search', name: nil, class: 'btn btn-outline-success my-2 my-sm-0'%>
  	    <% end %>
  	  </div>
  	</nav>
  	<p class="notice" style="display:none;"><%= notice %></p>
  	<p class="alert" style="display:none;"><%= alert %></p>
    <%= yield %>

  </body>
</html>